### ISSUE TITLE
Fliege-Maier grid orientation

### ISSUE THREAD

**Issue by HaHeho** [pyfar/pyfar#118]
## General

* pyfar version: `0.1.0`, but not sure which one exactly, since installed via `pip install git+...` a few days ago.

## Description

Generating Fliege-Maier grids with the refernced code yields coordinates in the expected format. However, the coordinates are different from e.g. from https://github.com/polarch/Spherical-Harmonic-Transform.

The reference to https://audiogroup.web.th-koeln.de/SOFiA_wiki/WELCOME.html does not really yield the source of your deposited data set. But I don't really mind that. ;)

It took us some time to make the Benni's and Archontis' conventions compatible to each other. For reference, what one seem to have to do is invert the `z` as well as exchange the `x` and `y` coordinates (Cartesian).

It is a spherical sampling grid, so there is not a false or right way of orienting the points, I suppose. However, it might be reasonable to use a common convention? Whaddaya think?

## What I Did

```python
grid = pyfar.samplings.sph_fliege()
coords = grid.get_sph(convention='top_elev', unit='rad')
``` 

## Labels

Label your issue to make it easier for us to assign and track:

**question** **samplings**

**Comment by f-brinkmann** [comment]
Yes - having identical conventions would be nice. I checked you proposal against Archontis version and against the Plots in the Fliege and Maier paper, and both comparisons looked correct. I'm making a pull for this :)
