### ISSUE TITLE
Review tests for first release

### ISSUE THREAD

**Issue by sikersten** [pyfar/pyfar#121]
## Description

Since many of the tests were implemented before testing guidelines were recently added, all previous contributors (@f-brinkmann, @mberz, @Agent49, @sikersten) are asked to review their tests before a first official release is published.

 - Pay attention to the new guidelines and feel free to reformulate parts of it or add information.
 - Consider to use sophisticated pytest functionalities (for example parametrization).
 - Remove all outdated or unnecessary tests.
 - Pay attention to imports and function calls. They should be implemented as they are done by non-developing users to implicitly test for correct init files. 
 - Consider to split the code into several pull requests for an easier review process.

**Comment by f-brinkmann** [comment]
Finished
