### ISSUE TITLE
Internal handling of SOS Filter coefficients

### ISSUE THREAD

**Issue by f-brinkmann** [pyfar/pyfar#13]
When we generate SOS-Filter-objects cross-over networks or fractional octave filters, the SOS can have different lengths. Currently, we add dummy SOSs, i.e., [1, 0, 0, 1, 0, 0] to make everything equal length.

This would cause additional and unnecessary filtering, if scipy does not catch the case.

We could add [None, None, None, None, None, None] instead and catch the case in the `process` class methods.

**Comment by mberz** [comment]
I'm unsure about the None type in the arrays, as it would results in a numpy array with a different type (object arrays) rather than simple np.float arrays. I'll look for an alternate solution.

**Comment by mberz** [comment]
Closed in #64
