### ISSUE TITLE
Handling of the FFT normalization in arithmetic operations

### ISSUE THREAD

**Issue by f-brinkmann** [pyfar/pyfar#224]
## General

* pyfar version: all

## Description

I thought about FFT normalization and arithmetic operations.

I see two goals:
1. Mathematically/physically correct operations
2. Uniform and therefore easy to understand handling (best everywhere in pyfar).

And two questions:
1. What do we do with the normalization before the operation?
2. What do we do with the normalization after the operation?

And here are my suggested answers:
1. Before the operation, I think we need to remove the normalization. This is the only consistent solution that gives correct results. If we don't remove the normalization, we would have to do different post-processing depending on the operation (`+`, `-`, `*`, `/`, `**`). e.g. the normalization (`n`) of two signals cancels out during division (`n * H1 / n * H2 = H1 / H2`) but during multiplication it in squares (`n * H1 * n * H2 = n**2 * H1 * H2`). There are more different cases that appear for different operations and if only one of the data has an FFT normalization. Currently we do remove the normalization before the operation (upon first glance). However, we handle it differently for Signal and FrequencyData objects. I think the reason for this is an error of thought in the FrequencyData implementation: #223
2. After the operation we can choose. Then the question is rather what is the most intuitive / explicit solution. Right now the result has the norm of the first audio object. Alternatively, we could return the result without normalization. I find the current variant more intuitive.

**Comment by mberz** [comment]
I think it makes sense here to only support physically meaningful operations. Yes, I'm going to talk abount energy and power signals again ;)

The norms and their corresponding signal type:

energy signal:
- 'none'

power signal:
- 'unitary'
- 'rms'
- 'amplitude'

power spectrum (s(t)^2):
- 'power'
- 'psd'

The resulting signal types per operation are then:

energy * energy = energy
energy / energy = energy
power * energy = power (i.e. white noise fed into a band-pass filter will result in band-pass filtered noise)
power * power = power spectrum (i.e. white noise spectrum multiplied with itself will be the power spectrum)
power / power = energy (i.e. IR measurement.)

power * power * power = ? Doesn't really have a physical meaning to me.

- Altogether this would result in following the norm of the power signal if multiplying an energy signal with a power signal. 
- Returning a power spectrum if multiplying two power signals. (De-normalize -> Set to 'power' norm)
- Raising an error if power * power spectrum
- Returning a 'none' normalized signal if dividing two power type signals.

**Comment by sikersten** [comment]
To my understanding, this would lead to the following rules (open for discussion, also note the ?):
* Addition, Subtraction: fft_norm of result is determined by first Signal
* For several operands, common math rules apply

| Multiplication | none      | unitary    | amplitude  | rms        | power | psd |
| -------------- | --------- | ---------- | ---------- | ---------- | ----- | --- |
| none           | none      | unitary    | amplitude  | rms        | power | psd |
| unitary        | unitary   | power/psd? | power/psd? | power/psd? | \-    | \-  |
| amplitude      | amplitude | power/psd? | power/psd? | power/psd? | \-    | \-  |
| rms            | rms       | power/psd? | power/psd? | power/psd? | \-    | \-  |
| power          | power     | \-         | \-         | \-         | \-    | \-  |
| psd            | psd       | \-         | \-         | \-         | \-    | \-  |

| Division (bottom/right) | none      | unitary | amplitude | rms  | power | psd |
| ----------------------- | --------- | ------- | --------- | ---- | ----- | --- |
| none                    | none      | \-      | \-        | \-   | \-    | \-  |
| unitary                 | unitary   | none    | none      | none | \-    | \-  |
| amplitude               | amplitude | none    | none      | none | \-    | \-  |
| rms                     | rms       | none    | none      | none | \-    | \-  |
| power                   | power     | ?       | ?         | ?    | ?     | ?   |
| psd                     | psd       | ?       | ?         | ?    | ?     | ?   |

**Comment by sikersten** [comment]
In the table above frequency domain operations are listed. In time domain, it is a little different for multiplication and division. I'm not completely sure, but I suspect that, from a physical point of view, fft_norm of the results (the type energy or power) depends on the signal itself. Multiplication examples:

- time window [none] * sine [amplitude] = windowed sine [none]
- a/t [none] * a*t [amplitude] = a^2 [amplitude]

We should consider that in #235 What do you think?

**Comment by f-brinkmann** [comment]
We should consider it. For the top example you could also argue that windowing is only a measure to force periodicity of the signal to make it more suitable for the FFT. From that point of view it could stay an amplitude signal, and we would be fine.

I think `pyfar.fft.normalization` can already account for windows, but not in interaction with `pyfar.Signals`

**Comment by sikersten** [comment]
As discussed in the weekly, we agree on the following for time domain ...
- Addition, Subtraction, Multiplication: same as frequency domain, see above. Though it is not strictly defined for multiplication from a theoretical point of view, convenience is the main argument.
- Division: due to missing examples for this operation, we choose the same rules as for frequency domain.
