### ISSUE TITLE
Better separation of Documentation and Concepts

### ISSUE THREAD

**Issue by f-brinkmann** [pyfar/pyfar#228]
## General

* pyfar version: 0.2.x

## Description

There are parts of the documentation that pertain to concepts of pyfar rather than documenting functions or classes. Examples are:
- [x]  Concept of Energy and Power signals (Simon)
- [x]  Explanation of coordinates systems (Fabian)
- [x]  Explanations of FFT related stuff (Simon, Alex)
- [x]  Explanations of signal arithmetics (Simon)
- [x]  Filter types (Fabian)

A possibility to speparate might be to add a section 'Concepts' to the docs. Parts of these section can be linked from the *real* documentation without loosing information and making the concepts easier to access at the same time.

**Comment by al-de** [comment]
In my opinion this is a great idea. I think your suggestion of adding a concepts section to the docs would be a good help for people just getting started with using pyfar.
