### ISSUE TITLE
Possibility to return time window

### ISSUE THREAD

**Issue by f-brinkmann** [pyfar/pyfar#242]
## General

* pyfar version: 0.2.3 

## Description

Should we make it possible for `pyfar.dsp.time_window` to return the window itself? This would be equivalent to pass a signal containing only ones. This would be more convenient if applying the same window at multiple points or to multiple signals.

**Comment by sikersten** [comment]
Suggestions:
- We could add a `return_window` parameter, which would return the windowed signal and the window as pyfar.Signal.
- For multiple signals, an alternative approach might be to merge these as channels in single one and apply `time_window` to it or to allow a tuple of signals as input.
- For multiple points, we could add a function which wraps ´time_window(..., crop='window')´ with the different positions as additional input parameter.

**Comment by f-brinkmann** [comment]
We decided in the weekly to go with the `return_window` parameter
