### ISSUE TITLE
Documentation not updated for develop branch

### ISSUE THREAD

**Issue by sikersten** [pyfar/pyfar#246]
## General

* pyfar version: 0.2.3

## Description

The documentation for the develop branch is not updated on [readthedocs](https://pyfar.readthedocs.io/en/develop/index.html). For example, the dsp/convolve is currently missing. We probably missed a setting somewhere?

**Comment by f-brinkmann** [comment]
I would suggest to drop develop from readthedocs.

**Comment by mberz** [comment]
Building the docs on rtd.org was simply broken due to dependency issues introduced by the use of the sofar and soundfile packages. I would vote for keeping building the develop docs for such cases.
