### ISSUE TITLE
Coefficients setter for filter classes

### ISSUE THREAD

**Issue by f-brinkmann** [pyfar/pyfar#249]
## General

* pyfar version: 0.2.3

## Description

The filter classes have a getter for `coefficients` but a setter is missing. Having a setter would make it possible to mimic time invariant systems by a block-wise update of the coefficients.

**Comment by mberz** [comment]
Didn't we decide to not implement this, as it would lead to unknown/invalid filter states?

**Comment by f-brinkmann** [comment]
Yes, I vaguely remember. In this case it would have been better to discuss before implementing - sorry for that.

For time variant systems, keeping the filter state and exchanging the coefficients would be correct. And I find using Filter objects for this is simpler than a manual OLA convolution.  
If someone wants to use Filter objects for time variant filtering, they have to manually initialize the filter state, since the state is `None` by default. I would thus argue that the setter adds another possibility without a high risk of users messing something up.

**Comment by mberz** [comment]
True, I was more thinking of users messing up their signals when forgetting to re-init the state if two consecutively filtered signals are not related. But thinking about it again, it makes sense to have these users re-init the state manually then. I'd be fine with this, if the documentation is clear about this and the intended use case.

**Comment by f-brinkmann** [comment]
Good point. I added documentation for that in #252
