### ISSUE TITLE
Set default interval of symmetric time_window function to length of signal

### ISSUE THREAD

**Issue by JMA-JMA** [pyfar/pyfar#250]
## General

* pyfar version: 0.2.3

## Description

In the function `time_window`, set the default interval for the default shape ``'symmetric'`` to length of the entire signal (i.e., `interval = [0,signalLength-1]`). By this, the function could be used similar to Matlab functions to quickly get a symmetric window (in Matlab, for example, `win = hann(signalLength)`, here, it would be `[windowedSig,win] = time_window(sig,return_window=True)`).

**Comment by mberz** [comment]
I'm not sure if I'm understanding this correctly, but from what you described, I'd suggest using the respective window function from scipy.signal is what you are looking for?

**Comment by JMA-JMA** [comment]
Thanks for the hint. Looks like scipy.signal.get_window is doing exactly this, yes. So maybe we close this issue here, as it is not implementable straight forward in pyfar anyway. Worked on it yesterday a little, but it makes the function structure uncessarily confusing when setting this as a default only for the 2-entry interval and 'unit' = samples. I can live with the workaround setting the interval or using scipy directly...

**Comment by mberz** [comment]
Alright then, I'll close the issue for now.

:+1: for keeping the individual functions as simple as possible.
