### ISSUE TITLE
dB Parameters in dsp.spectrogram

### ISSUE THREAD

**Issue by f-brinkmann** [pyfar/pyfar#257]
## General

* pyfar version: 0.23

It was suggested to remove the dB parameters from `dsp.spectrogram` and only have them in `plot.spectrogram`. Do we want this and how would we handle the broken backwards compatability.

**Comment by sikersten** [comment]
Until merging pull request #256 into develop the dB parameter had no effect for `dsp.spectrogram`, right? 
So, I would consider it as a bugfix to just remove it from `dsp.spectrogram` and only have a dB parameter for `plot.spectrogram`.

**Comment by f-brinkmann** [comment]
Good point! We already merged #256 and decided to make this a separate issue and Pull request. But since we only merged into Develop we could still do that. Is every one fine with Simon's suggestion?
