### ISSUE TITLE
dB function

### ISSUE THREAD

**Issue by sikersten** [pyfar/pyfar#288]
## General

* pyfar version: 0.4.0

## Description

A decibel function would be a nice feature! So instead of calling, e.g., `20*np.log10(abs(signal.freq))` it could have the structure `pyfar.dsp.decibel(signal, domain='freq', log_prefix=None, log_reference=1)` with reasonable defaults. Similar to other functions in the dsp module, it would operate on an Audio object and returns an array.
In the weekly, we also discussed the option of adding corresponding properties to the Audio objects, but then the parameters  ´log_prefix´ and ´log_reference´ would be missing. Alternatively, methods `signal.freq_dB(log_prefix, log_reference)`, `signal.time_dB(log_prefix, log_reference)`, `signal.freq_raw_dB(log_prefix, log_reference)` with appropriate defaults could be added.

What do you prefer?

**Comment by f-brinkmann** [comment]
We decided to only implement the function, without adding class methods to the audio classes.
