### ISSUE TITLE
contourf option for 2d plots

### ISSUE THREAD

**Issue by sikersten** [pyfar/pyfar#289]
## General

* pyfar version: 0.4.0

## Description

Currently, the 2d plot functions work with matplotlib's [pcolormesh](https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.pcolormesh.html#matplotlib.axes.Axes.pcolormesh) in the background. For some applications [contourf](https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.contourf.html?highlight=contourf#matplotlib.axes.Axes.contourf) might be the better option. Let's elaborate, if it makes sense to add parameter for that to the plot functions (e.g., `backend=pcolormesh`). A basis for the discussion could be this [example](https://matplotlib.org/stable/gallery/images_contours_and_fields/pcolormesh_levels.html#making-levels-using-norms), which illustrates the possible implementation of a `levels` parameter.

**Comment by sikersten** [comment]
Issue #290 might be relevant with respect to the compatibility of the underlying grids.

**Comment by f-brinkmann** [comment]
After #290 is closed, the grids should be compatible and I would be in favor of adding this option. The only tricky thing might be the handling in interaction.
