### ISSUE TITLE
Use of crossover filter on multi-channel data

### ISSUE THREAD

**Issue by RoyJames** [pyfar/pyfar#295]
Hi,

Thank you for developing this package. I have a question while using it. Suppose I have decomposed a signal into subbands by doing
```
output = pyfar.dsp.filter.fractional_octave_bands(signal, 1)
bands, _ = pyfar.dsp.filter.fractional_octave_frequencies(1)
```
and want to combine them back using
```
combined = pyfar.dsp.filter.crossover(output, 4, bands)
```
Maybe I'm not understanding the DSP enough: I thought each channel in `output` would be filtered by one corresponding band-pass (and low or high-pass) filter in the crossover filters so that I can combine the filtered channels them into a "full-band" signal. But the above process gives me the `combined` signal shaped as a 10 x 10 x `signal_len`. Reading the code for `filter.process()` seems it is designed to be this way.
https://github.com/pyfar/pyfar/blob/83a1fca284f0b0a33a06fecf2f4f2ba6bf672c33/pyfar/classes/filter.py#L228-L232

My question is if this is by design, doesn't this scheme create a lot of redundancies, because when doing crossover we'd expect to do N filterings instead of NxN (or am I wrong here), and I'm only going to add up `combined[i][i]` for each channel?

Thanks,
Zhenyu

**Comment by f-brinkmann** [comment]
Hi Zhenyi,

`fractional_octave_bands` and `crossover` are both filter banks, i.e., they will always return more channels than the original signal had. You can find examples for them in the newly introduced concepts: https://pyfar.readthedocs.io/en/latest/concepts/pyfar.filter_types.html

If you want to join the signals after processing you'll have to manually sum them, as there is currently no function to do that:

```python
import numpy as np

output_joined = output.copy()
output_joined.time = np.sum(output_joined.time, 0)
```

Note that `fractional_octave_bands` is not perfectly reconstructing, this means, that `output_joined` will not be the same as output. If this is required you should consider [reconstructing_fractional_octave_bands](https://pyfar.readthedocs.io/en/latest/modules/pyfar.dsp.filter.html#pyfar.dsp.filter.reconstructing_fractional_octave_bands)

Best, Fabian
