### ISSUE TITLE
read_sofa could take Sofa objects and filenames as input

### ISSUE THREAD

**Issue by f-brinkmann** [pyfar/pyfar#296]
## Description

`pyfar.io.read_sofa` currently only accepts the name of a SOFA file as input. For convenience it could also take a `sofar.Sofa` object as input in case someone already loaded the SOFA file. This would be very ease to implement.

**Comment by sikersten** [comment]
In the weekly, we discussed to have that functionality preferably in a different function, e.g., `pyfar.io.convert_sofa`.
