### ISSUE TITLE
Duplicate mocks

### ISSUE THREAD

**Issue by f-brinkmann** [pyfar/pyfar#30]
there are identical mocks in different test files - should we move all mocks to a single file for a better overview and reusability?

**Comment by mberz** [comment]
Yes, I have thought about that as well. I think this makes sense. This would also make testing the mocks simpler and more compact.

**Comment by Agent49** [comment]
Definitely, don't repeat yourself! Everything else makes maintenance harder.

**Comment by mberz** [comment]
I like the idea of having a separate file for the mocks, that way one can simply check in there for existing mocks and not search through a lot of separate file.

**Comment by Agent49** [comment]
Actually I also think it's a good idea to have all of them in a seperate file, not at least for consistency. We still can  `from mock import my_mock` to only import whats really used in the test. 

Btw. do we whant to gitignore the generated SOFA files or wouldn't be better to hardwire the data?

**Comment by mberz** [comment]
> Actually I also think it's a good idea to have all of them in a seperate file, not at least for consistency. We still can `from mock import my_mock` to only import whats really used in the test.

Yes, that's what I was thinking of. The file should also have it's respective tests of course.

> Btw. do we whant to gitignore the generated SOFA files or wouldn't be better to hardwire the data?

Please stick to the issue at hand. This is a separate issue; I have openend one in #41

**Comment by sikersten** [comment]
An alternative would be to implement the mocks in a `conftest.py`: https://docs.pytest.org/en/stable/fixture.html#conftest-py-sharing-fixture-functions

**Comment by sikersten** [comment]
In our current test implementations we often declare the mocks as pytest fixtures. I think it is unnecessary to do so, as our mocks do not serve the purpose of _setting up services, state, or other operating environments_ (see https://docs.pytest.org/en/stable/fixture.html). So implementing them in conftest.py would be the wrong way. Please comment, if I'm missing something.

**Comment by f-brinkmann** [comment]
It says that fixtures '_may_  setup services, state, or other operating environments'  - so I assume you can also use them for other stuff...
