### ISSUE TITLE
Time plot is buggy when plotting several signals of different lengths in one figure

### ISSUE THREAD

**Issue by tjueterb** [pyfar/pyfar#306]
## General

* pyfar version: 0.4.1
* Python version: 3.8.13 
* Operating System: macOS 12.3
* Did you install pyfar via pip: yes

## Description

I wanted to plot a signal (441 samples) and a window function (25 samples) in the same plot. 
After the second plot command the axis switched from ms to µs, the window was displayed correctly but the original signal was downscaled as if the plot did not correctly convert the signal vom ms to µs. 

## What I Did

```
import pyfar as pf
import matplotlib.pyplot as plt

x = pf.signals.sine(n_samples=441,frequency=250)
y = pf.signals.sine(n_samples=25, frequency=250)

plt.figure()
pf.plot.time(x)
plt.figure()
pf.plot.time(y)
plt.figure()
pf.plot.time(x)
pf.plot.time(y)
```

## Labels

**hot**, **plot**

![plot1](https://user-images.githubusercontent.com/38947363/165518321-2612aab7-7b8e-4dbd-b624-8dbd0ff52011.png)
![plot2](https://user-images.githubusercontent.com/38947363/165518334-2de5d65e-b9b3-4a27-b975-62d27a004387.png)
![plot3](https://user-images.githubusercontent.com/38947363/165518337-36d8d42f-0001-425b-a16d-8112ebedba72.png)

**Comment by f-brinkmann** [comment]
This is known behavior and we tolerate it for the convenience of having nice auto units. The quick workaround is to use the `unit` parameter of the plot function. A general solution would be to look for existing units by checking the axis label. We could discuss this in the group and see if someone finds time to for implementation...

**Comment by tjueterb** [comment]
That solves the problem, thanks @f-brinkmann @mberz !

**Comment by mberz** [comment]
I'm reopening this, as this definitely is unwanted default behavior.

**Comment by f-brinkmann** [comment]
We decided to change the default parameter of `unit` to `s` and introduce `unit='auto'` for auto-uniting and a deprecation warning for `unit=None`.
