### ISSUE TITLE
CI: Test documentation

### ISSUE THREAD

**Issue by f-brinkmann** [pyfar/pyfar#314]
We lost testing the Sphinx documentation when switching from Travis to Circle CI

**Comment by mberz** [comment]
The documentation was never actually tested on Travis as far as I remember.
Are you sure we had this?

**Comment by f-brinkmann** [comment]
I think I remember fixing rather unimportant warning in the docs due to this, but I might be wrong. Wouldn't it be good to have this anyhow?
