### ISSUE TITLE
Broadcasting in arithmetic operations

### ISSUE THREAD

**Issue by sikersten** [pyfar/pyfar#317]
## General

* pyfar version: 0.4.2

## Description

During the implementation of PR #277 I stumbled across the following problem:
The docstrings of the arithmetic operations state that combinations of array likes and audio objects are allowed. For N-D signals, this is not quite intuitive. For example, a channelwise amplification raises a broadcasting error
```
a = np.arange(2 * 3 * 4).reshape((2, 3, 4))
b = np.ones((2, 3, 4))
d = a * pf.signals.impulse(10, amplitude=b)
```
So, the internal broadcasting along the time/frequency dimension of the array is missing, while this works:
```
a = np.arange(2 * 3 * 4).reshape((2, 3, 4, 1))
b = np.ones((2, 3, 4))
d = a * pf.signals.impulse(10, amplitude=b)
```
And even this
```
a = np.arange(2 * 3 * 4 * 6).reshape((2, 3, 4, 6))
b = np.ones((2, 3, 4))
d = a * pf.signals.impulse(10, amplitude=b)
```

**Comment by f-brinkmann** [comment]
ah, ok. Then adding an axis `b = b[..., np.newaxis]` before the internal multiplication might already solve the issue (maybe with an if case, not sure)

**Comment by sikersten** [comment]
Note: the examples above only work on the [feature/matrix_multiplication](https://github.com/pyfar/pyfar/tree/feature/matrix_multiplication) branch, where an
```
# indicate use of _Audio arithmetic operations (e.g. __rmatmul__)
__array_priority__ = 1.0
```
was added to the audio class.

**Comment by mberz** [comment]
> Note: the examples above only work on the [feature/matrix_multiplication](https://github.com/pyfar/pyfar/tree/feature/matrix_multiplication) branch, where an
> ```
> # indicate use of _Audio arithmetic operations (e.g. __rmatmul__)
> __array_priority__ = 1.0
> ```
> was added to the audio class. 

If that's a separate commit, you could try cherry-picking it.
