### ISSUE TITLE
Outdated Docstrings for arithmetic operations

### ISSUE THREAD

**Issue by f-brinkmann** [pyfar/pyfar#320]
## General

* pyfar version: 0.4.2

## Description

The docstrings of the arithmetic functions are outdated. They must reflect the rules listed here: https://pyfar.readthedocs.io/en/develop/concepts/pyfar.arithmetic_operations.html

**Comment by sikersten** [comment]
Let's also update the docstring for the ``domain`` parameter, as suggested in the review of #277:
Suggestion by @f-brinkmann: "Frequency domain operations work on the raw spectrum."
