### ISSUE TITLE
Feature: read comsol exports

### ISSUE THREAD

**Issue by sikersten** [pyfar/pyfar#335]
## General

* pyfar version: 0.4.2

## Description

What do you think of a function to read files exported from Comsol (.txt or .csv), which automatically extracts the data incl. frequencies, labels etc.? Would it be a good function for pyfar.io?

**Comment by ahoelter** [comment]
Good idea. I am not very familiar with Comsol. Then, I think a structure to store parameters (environmental conditions, initial values, etc.) of the simulation as a dict would be nice. And maybe also the possibility to store the data with different units (density, velocity, pressure). Just my first thoughts.

**Comment by mberz** [comment]
@sikersten Makes sense, but this potentially involves handling a lot of differerent naming conventions, depending on what one does export from COMSOL.

@ahoelter Simulation parameters specific to COMSOL are beyond a general use package such as pyfar, you may want to have a look at https://mph.readthedocs.io/en/stable/ .

**Comment by sikersten** [comment]
@mberz What kind of naming conventions to you refer to?
What I was thinking of were these [data formats](https://doc.comsol.com/6.0/docserver/#!/com.comsol.help.comsol/comsol_api_fileformats.50.03.html) and [these examples](https://doc.comsol.com/6.0/doc/com.comsol.help.comsol/comsol_ref_definitions.17.053.html#1731640).
Anne and I discussed that probably a dict incl. the coordinates, one audio object per _Expression_ and the meta data from the file makes sense to return. The corresponding keys could match the corresponding expressions extracted from the header. As far as I see, the only parameter (convention?) needed to be handled - in case we want to inlcude both - is the "Data Format: Spreadsheet" vs. "Data Format: Sectionwise". Units could be stored in the comments of the audio objects.

**Comment by mberz** [comment]
I meant the kind of data exported: pressure, velocity, intensity, etc. The names seem to depend on the language of the comsol installation. 
I would opt for using TimeData or FrequencyData to avoid issues with incomplete Fourier spectra or non uniform sampling.
