### ISSUE TITLE
Mybinder is missing libsndfile

### ISSUE THREAD

**Issue by ahms5** [pyfar/pyfar#337]
## General

* pyfar version: 0.4.2
* Python version:
* Operating System: Windows 10

## Description

examples notebook: cannot import soundfile (pyfar)
might be fixed with issue #332

**Comment by f-brinkmann** [comment]
what is the error you are getting? I'm on Windows 10 and it's working for me

**Comment by ahms5** [comment]
I should have added it before: here is the error for executing the import of the packages:
`# import packages
import pyfar as pf
import numpy as np`

`---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
/tmp/ipykernel_42/2971463473.py in <module>
      1 # import packages
----> 2 import pyfar as pf
      3 import numpy as np

/srv/conda/envs/notebook/lib/python3.7/site-packages/pyfar/__init__.py in <module>
     16 from . import plot
     17 from . import samplings
---> 18 from . import io
     19 from . import dsp
     20 from . import signals

/srv/conda/envs/notebook/lib/python3.7/site-packages/pyfar/io/__init__.py in <module>
----> 1 from .io import (read_wav, write_wav, read, write, read_sofa,
      2                  read_audio, write_audio,
      3                  audio_subtypes, audio_formats, default_audio_subtype)
      4 
      5 

/srv/conda/envs/notebook/lib/python3.7/site-packages/pyfar/io/io.py in <module>
     19 
     20 try:
---> 21     import soundfile
     22     soundfile_imported = True
     23 except ModuleNotFoundError or OSError:

/srv/conda/envs/notebook/lib/python3.7/site-packages/soundfile.py in <module>
    140     _libname = _find_library('sndfile')
    141     if _libname is None:
--> 142         raise OSError('sndfile library not found')
    143     _snd = _ffi.dlopen(_libname)
    144 except OSError:

OSError: sndfile library not found`

**Comment by ahms5** [comment]
same problem with different browser, i tried Chrome and Firefox

**Comment by f-brinkmann** [comment]
I see - thats the lib-soundfile issue. I wonder why the OSError is raised although we are doing this in a try statement. Can you trythe changed exception handling below?

```python
except (ModuleNotFoundError, OSError):
    soundfile_imported = False
    soundfile_warning = (
        "python-soundfile could not be imported. Try to install it using `pip "
        "install soundfile`. If this not works search the documentation for "
        "help: https://python-soundfile.readthedocs.io")
```

I could only test the ModuleNotFoundError on my machine and thought that `or` statements work in exception, but they might not.

**Comment by ahms5** [comment]
not sure how to test it, without changing the main branch, since this errer just appear if I use this [link](https://mybinder.org/v2/gh/pyfar/pyfar/main?filepath=examples%2Fpyfar_demo.ipynb): locally it is working well

**Comment by mberz** [comment]
Seems to me that this is a different issue. libsndfile is simply not getting installed on the mybinder instance.

**Comment by mberz** [comment]
Just re-opening as I only merged the workaround, not the actual fix. Reading/writing a file on binder will still fail without #341
