### ISSUE TITLE
Data type for audio objects

### ISSUE THREAD

**Issue by f-brinkmann** [pyfar/pyfar#343]
## General

* pyfar version: all

Problem: The audio classes have the dtype argument, but it is not used

Solution:
- FrequencyData and TimeData should keep it, to make it possible to store real valued spactra and complex valued time signals
- Signal.time is always double, Signal.freq always complex.
- The new dtype default will be None in all cases and the dtype is inferred from the input data if not passed

**Comment by sikersten** [comment]
I'm not sure if it really makes sense to be able to store complex valued time signals. We should check first if all functions that are able to handle both TimeData and Signal objects would not lead to strange results or errors (and not implicitly rely on real valued data).

**Comment by f-brinkmann** [comment]
Good point. Basically everything will probably break with complex time data...
