### ISSUE TITLE
Support for Python version 3.7

### ISSUE THREAD

**Issue by sikersten** [pyfar/pyfar#347]
## General

* pyfar version: 0.4.3
* Python version: 3.8 -

## Description

Numpy dropped the support for Python version 3.7 with [release 1.22](https://numpy.org/doc/stable/release/1.22.0-notes.html). We should consider to drop the support accordingly, as a lot of pyfar's functionality heavily relies on numpy.
This was highlighted within PR #339, where the test for 3.7 failed due to changes in numpy's ``loadtxt``.

**Comment by f-brinkmann** [comment]
I would be fine with dropping it for the next release.

**Comment by mberz** [comment]
I'd drop it with the next release. We'll only run into dependency hell if we don't.
