### ISSUE TITLE
Documentation examples for fractional delay fail

### ISSUE THREAD

**Issue by mberz** [pyfar/pyfar#349]
## General

* pyfar version: develop

## Description

Building the documentation fails for the examples for fractional delay function.

See:
https://app.circleci.com/pipelines/github/pyfar/pyfar/270/workflows/7fc7df39-77b5-41cf-af5b-e51e0aa296d2/jobs/1456

**Comment by f-brinkmann** [comment]
I think I fixed this (in bad practice) as part of another pull-request. Lets wait if this still happens after merging open pulls.

**Comment by mberz** [comment]
Dude, if you don't stop doing this, we'll really need to start a penalty system where you buy everyone else a pack of beers each every time this happens!

**Comment by f-brinkmann** [comment]
Does Sterni count as beer?
