### ISSUE TITLE
Audio Classes do not allow data for a single time/frequency

### ISSUE THREAD

**Issue by f-brinkmann** [pyfar/pyfar#360]
## General

but they should

**Comment by twennemann** [comment]
I was trying to reproduce the issue with: 
`signal = pf.Signal([1], 44100)
signal2 = pf.TimeData([1],[1])
singal3 = pf.FrequencyData([1],[1])`
but that works as it's supposed to. What is the exact issue here?

**Comment by sikersten** [comment]
Maybe it refers to the fact that an initialization of a Signal in frequency domain with only one bin leads to an error?
`pf.Signal([1], 44100, domain='freq', n_samples=1)`
without `n_samples=1` causes
`ZeroDivisionError: float division by zero`
