### ISSUE TITLE
Improve show() function for coordinates objects

### ISSUE THREAD

**Issue by f-brinkmann** [pyfar/pyfar#364]
## General

Plots of coordinates could look better. See if new features of Matplotlib can be used:
https://matplotlib.org/stable/users/prev_whats_new/whats_new_3.6.0.html#custom-focal-length-for-3d-camera
https://matplotlib.org/stable/users/prev_whats_new/whats_new_3.6.0.html#equal-aspect-ratio-for-3d-plots

**Comment by sikersten** [comment]
I'd suggest to handle this in combination with  #353

**Comment by f-brinkmann** [comment]
Absolutely, but I thought of making it in two separate pulls in any order to keep the code changes small and more easy to review.

**Comment by ahms5** [comment]
Do we need more or is #554 sufficient for this issue?

**Comment by f-brinkmann** [comment]
This would work for me already. I think we discussed at some point that the show method should move to the plot module at some point. But i'll open a separate issue for that.
