### ISSUE TITLE
Remove AUTHORS.rst

### ISSUE THREAD

**Issue by sikersten** [pyfar/pyfar#375]
## Description

The [contribution details](https://github.com/pyfar/pyfar/graphs/contributors) provided by Github make the credits in [AUTHORS.rst](https://github.com/pyfar/pyfar/blob/main/AUTHORS.rst) obsolete. We should consider to remove it.

**Comment by f-brinkmann** [comment]
+1 - I would be fine with only writing 'The pyfar developers' at places where authors are usually mentioned.
