### ISSUE TITLE
Plots don't show without `matplotlib.pyplot.show()` 

### ISSUE THREAD

**Issue by dired** [pyfar/pyfar#376]
## General

* pyfar version: 0.5.0
* Python version: 3.10.8
* Operating System: Windows
* Did you install pyfar via pip: Yes

## Description

I was following the examples from the docs, e.g.
```py
import pyfar as pf
import sounddevice as sd
# Load, illustrate and play speech signal
speech = pf.signals.files.speech()
pf.plot.spectrogram(speech)
sd.play(speech.time.T, speech.sampling_rate)
```
.

What happened: The program exited successfully.
What went wrong: No plot - no plot window came up at all.
What I expected to happen: Plot window comes up, just like with the minimal matplotlib example (which works)

## What I Did

An example I already gave you, instead here I write what fixed the plot not showing
```py
import pyfar as pf
import sounddevice as sd
import matplotlib.pyplot   # <- fix here
# Load, illustrate and play speech signal
speech = pf.signals.files.speech()
pf.plot.spectrogram(speech)
sd.play(speech.time.T, speech.sampling_rate)
matplotlib.pyplot.show()    # <- fix here
```

## Labels

**bug**, **enhancement**
(not sure how to label the issue here)

Second label: **plot**

## Project

**Do not assign your issue to a project.** This is done automatically.

**Comment by f-brinkmann** [comment]
Thanks for reporting - I also have the issue and checked our code. We are indeed missing the `plt.show()` in our plot functions. It worked before for some reason. We'll look into it.

**Comment by mberz** [comment]
I've also encountered this issue, seems to be related to changes in recent matplotlib versions.
As you pointed out, explicitly calling `show()` currently is the best wortkaround.

**Comment by f-brinkmann** [comment]
ok - I'll do a pull for that.

**Comment by mberz** [comment]
I don't think this is an issue caused by pyfar.

@dired Could you please give more information on your environment and the matplotlib backend you're using.

Automatically showing figures is handled by the matplotlib backend and not by pyfar.
Interactive backends automatically show plots for each code cell. Please see [here](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.ion.html#matplotlib.pyplot.ion) and [here](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.show.html) for information on backend selection or manually setting interactive mode.

**Comment by dired** [comment]
Hey, thanks for the comments.

I don't know how it is intended on either sides, what I derive for myself from the "minimal matplotplib example" (what I meant earlier) is that the `.show()` is needed. I would assume then that it will be needed if matplotlib is used as a dependency in another package (like pyfar). The example being:
```py
import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(0, 2 * np.pi, 200)
y = np.sin(x)

fig, ax = plt.subplots()
ax.plot(x, y)
plt.show()
```
[[Source](https://matplotlib.org/stable/users/getting_started/index.html#installation-quick-start)]

After looking through your codebase for a longer time, I found out that e.g. `spectrogram` from `pyfar\plot\two_d.py` and all the other plot-functions return `ax`-objects. "Who" magically receives it and displays it on the screen remains a mystery to me, it does not seem to be written in code anywhere explicitly. 

My guess was that by installing and using a backend, it would implicitly be received somewhere by the backend and show, but the plot does not come up automagically either, after installing `PyQt5` and using it with `matplotlib.use('Qt5Agg')`.

Your suggestion @mberz applies in interactive mode, where if activated with `.ion()`, a plot comes up when activating a specific cell / pressing enter in the python interactive mode - but it doesn't help with non-interactive execution.

My "degenerate" / new-to-matplotlib conclusion would be that if a library uses matplotlib, using `.show()` is needed and "it's not there" in the codebase. Of course I expect to be proven wrong here. 

One cause that I can think of, for it to have worked before and since this appears to be a completely new behavior, is that matplotlib introduced this need for `.show()`. In fact, when looking at [older matplotlib documentation (version 3.4.3)](https://matplotlib.org/3.4.3/tutorials/introductory/usage.html#sphx-glr-tutorials-introductory-usage-py), there actually does not seem to be the necessity for `.show()`.

@mberz since you wanted more information on my environment, I also tried the code on another pc running ubuntu. In both cases they run very recent versions of python and pip modules.

### First env:
Windows 11 22H2 (22621)
Python 3.10.8
<details>
  <summary> Pip modules and versions </summary>

  ```s
anyio==3.6.2
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
asttokens==2.0.8
attrs==22.1.0
Babel==2.10.3
backcall==0.2.0
beautifulsoup4==4.11.1
bleach==5.0.1
certifi==2022.9.24
cffi==1.15.1
cftime==1.6.2
charset-normalizer==2.1.1
colorama==0.4.5
contourpy==1.0.5
cycler==0.11.0
debugpy==1.6.3
decorator==5.1.1
deepdiff==6.2.1
defusedxml==0.7.1
entrypoints==0.4
executing==1.1.1
fastjsonschema==2.16.2
fonttools==4.38.0
idna==3.4
ipykernel==6.16.1
ipython==8.5.0
ipython-genutils==0.2.0
jedi==0.18.1
Jinja2==3.1.2
json5==0.9.10
jsonschema==4.16.0
jupyter-server==1.21.0
jupyter_client==7.4.3
jupyter_core==4.11.2
jupyterlab==3.5.0
jupyterlab-pygments==0.2.2
jupyterlab_server==2.16.1
kiwisolver==1.4.4
MarkupSafe==2.1.1
matplotlib==3.6.1
matplotlib-inline==0.1.6
mistune==2.0.4
nbclassic==0.4.5
nbclient==0.7.0
nbconvert==7.2.2
nbformat==5.7.0
nest-asyncio==1.5.6
netCDF4==1.6.1
notebook==6.5.1
notebook_shim==0.2.0
numpy==1.23.4
ordered-set==4.1.0
packaging==21.3
pandocfilters==1.5.0
parso==0.8.3
pickleshare==0.7.5
Pillow==9.2.0
prometheus-client==0.15.0
prompt-toolkit==3.0.31
psutil==5.9.3
pure-eval==0.2.2
pycparser==2.21
pyfar==0.5.0
Pygments==2.13.0
pyparsing==3.0.9
PyQt5==5.15.7
PyQt5-Qt5==5.15.2
PyQt5-sip==12.11.0
pyrsistent==0.18.1
python-dateutil==2.8.2
pytz==2022.5
pywin32==304
pywinpty==2.0.8
pyzmq==24.0.1
requests==2.28.1
scipy==1.9.3
Send2Trash==1.8.0
six==1.16.0
sniffio==1.3.0
sofar==0.3.1
sounddevice==0.4.5
soundfile==0.11.0
soupsieve==2.3.2.post1
stack-data==0.5.1
terminado==0.16.0
tinycss2==1.2.1
tomli==2.0.1
tornado==6.2
traitlets==5.5.0
urllib3==1.26.12
wcwidth==0.2.5
webencodings==0.5.1
websocket-client==1.4.1
  ```
</details>

### Second env
Ubuntu 22.04.1 LTS
Python 3.10.6
<details>
  <summary> Pip modules and versions </summary>

  ```s
aiohttp==3.8.1
aiosignal==1.2.0
ansible-base==2.10.8
apache-libcloud==3.2.0
apt-offline==1.8.4
apturl==0.5.2
argcomplete==1.8.1
asn1crypto==1.4.0
async-timeout==4.0.1
attrs==21.2.0
Babel==2.8.0
bcrypt==3.2.0
beautifulsoup4==4.11.1
blinker==1.4
Brotli==1.0.9
catfish==4.16.3
certifi==2020.6.20
cffi==1.15.0
cftime==1.6.2
chardet==4.0.0
charset-normalizer==2.0.6
click==8.0.3
colorama==0.4.4
command-not-found==0.3
contourpy==1.0.6
cryptography==3.4.8
cupshelpers==1.0
cycler==0.11.0
dbus-python==1.2.18
decorator==4.4.2
deepdiff==6.2.1
defer==1.0.6
distlib==0.3.4
distro==1.7.0
distro-info===1.1build1
dnspython==2.1.0
filelock==3.6.0
fonttools==4.38.0
frozenlist==1.2.0
gpg===1.16.0-unknown
gssapi==1.6.12
gyp==0.1
httplib2==0.20.2
idna==3.3
ifaddr==0.1.7
importlib-metadata==4.6.4
indicator-cpufreq==0.2.2
jeepney==0.7.1
Jinja2==3.0.3
jmespath==0.10.0
keyring==23.5.0
keyrings.alt==4.1.0
kiwisolver==1.4.4
language-selector==0.1
launchpadlib==1.10.16
lazr.restfulclient==0.14.4
lazr.uri==1.0.6
lightdm-gtk-greeter-settings==1.2.2
lockfile==0.12.2
lz4==3.1.3+dfsg
Mako==1.1.3
Markdown==3.3.6
MarkupSafe==2.0.1
matplotlib==3.6.1
menulibre==2.2.2
meson==0.61.2
more-itertools==8.10.0
mugshot==0.4.3
multidict==5.1.0
netaddr==0.8.0
netCDF4==1.6.1
netifaces==0.11.0
ntlm-auth==1.4.0
numpy==1.23.4
oauthlib==3.2.0
olefile==0.46
onboard==1.4.1
ordered-set==4.1.0
packaging==21.3
paramiko==2.9.3
pexpect==4.8.0
Pillow==9.0.1
platformdirs==2.5.1
ply==3.11
psutil==5.9.0
ptyprocess==0.7.0
pycairo==1.20.1
pycparser==2.21
pycryptodomex==3.11.0
pycups==2.0.1
pycurl==7.44.1
pyfar==0.5.1
Pygments==2.11.2
PyGObject==3.42.1
pyinotify==0.9.6
PyJWT==2.3.0
pykerberos==1.1.14
PyNaCl==1.5.0
PyOpenGL==3.1.5
pyparsing==2.4.7
PyQt5==5.15.7
PyQt5-Qt5==5.15.2
PyQt5-sip==12.11.0
PySimpleSOAP==1.16.2
python-apt==2.3.0+ubuntu2.1
python-dateutil==2.8.1
python-debian===0.1.43ubuntu1
python-debianbts==3.2.0
python-magic==0.4.24
pytz==2022.1
pywinrm==0.3.0
pyxdg==0.27
PyYAML==5.4.1
qrencode==1.2
rencode==1.0.6
reportlab==3.6.8
requests==2.25.1
requests-kerberos==0.12.0
requests-ntlm==1.1.0
requests-toolbelt==0.9.1
requests-unixsocket==0.2.0
scipy==1.9.3
screen-resolution-extra==0.0.0
SecretStorage==3.3.1
selinux==3.3
setproctitle==1.2.2
sgt-launcher==0.2.7
simplejson==3.17.6
six==1.16.0
sofar==0.3.1
sounddevice==0.4.5
soundfile==0.11.0
soupsieve==2.3.2.post1
ssh-import-id==5.11
systemd-python==234
typing-extensions==3.10.0.2
ubuntu-advantage-tools==27.10
ubuntu-drivers-common==0.0.0
ufw==0.36.1
unattended-upgrades==0.1
urllib3==1.26.5
virtualenv==20.13.0+ds
wadllib==1.3.6
xcffib==0.11.1
xdg==5
xkit==0.0.0
xmltodict==0.12.0
yarl==1.7.2
zeroconf==0.38.3
zipp==1.0.0
zope.interface==5.4.0
</details>

**Comment by mberz** [comment]
@dired How are you executing your code? Are you using VSCode, JupyterLab, or something different?

**Comment by dired** [comment]
> @dired How are you executing your code? Are you using VSCode, JupyterLab, or something different?

I use VSCode, but I execute my scripts as I'm used to, in so-to-say external terminals or in the built-in terminal (which of course is just like an external terminal) via `python3 script.py`.

**Comment by mberz** [comment]
@dired Thanks for your update.

The behavior you are reporting is matplotlib's default behavior (since v1.0.0), which we do not intend to modify, as it would lead to inconsistencies with matplotlib. If you're not using interactive mode, you'll need to tell matplotib to show the plots manually using `plt.show()`.
If you're using VSCode's interactive code execution, there's currently potentially also other issues involved, since VSCode does not support the most recent version of ipywidgets (>=8), see https://github.com/microsoft/vscode-jupyter/issues/11336

**Comment by dired** [comment]
> If you're not using interactive mode, you'll need to tell matplotib to show the plots manually using `plt.show()`. 

Good, this should be "made known" for everyone I guess - I think this information might be of lack in some places of documentation/introduction.

I can live with that and regard this issue as solved then.

Regarding interactive code execution: I have had no problem with jupyter notebooks, I believe I have also seen another kind of interactive mode used by @f-brinkmann in vscode (or that was nothing else than jupyter). I should or have to try it out sometime.

**Comment by f-brinkmann** [comment]
@dired I'm making use of cells that are defined by `# %%` and can be executed with *str + return*. That's a VSCode specific feature, which opens an interactive Python kernel to which the commands are being send.

**Comment by f-brinkmann** [comment]
`plt.show` is required for non-interactive backends. Thus closing this...
