### ISSUE TITLE
pfar/applications

### ISSUE THREAD

**Issue by f-brinkmann** [pyfar/pyfar#38]
I image that there might be lots of useful tools based on pyfar in the future that are worth keeping track of. What would be the best way of collecting them? Would it be good to have one repository for applications based on pyfar?

**Comment by f-brinkmann** [comment]
Applications will be single packages. We will look for a good way to gather available applications in a central space (repo, pyfar.org)

**Comment by mberz** [comment]
Closing, since this has been resolved.
