### ISSUE TITLE
Normalize fails for TimeData, FrequencyData containing nan elements

### ISSUE THREAD

**Issue by mberz** [pyfar/pyfar#389]
## General

* pyfar version: v0.5.x

## Description

`pyfar.dsp.normalize` fails if the input data contains nans, normalizing the result to contain nan values only.
This only affects `TimeData` and `FrequencyData` which support storing nan values.

**Comment by f-brinkmann** [comment]
I wasn't aware that those should be able to hold NaNs. I'm not sure if we are testing that anywhere. If it is the case, we should probably add tests for all functions that accept TimeData and FrequencyData objects.
