### ISSUE TITLE
Signal - un-normalized spectrum

### ISSUE THREAD

**Issue by f-brinkmann** [pyfar/pyfar#39]
## Description

Many processing applications require the DFT spectrum without any normalization. Should be provide a getter for that in Signal? This might avoid errors of users handling this wrongly and save duplicate code.

**Comment by mberz** [comment]
Could you give an example?
I see your point, but this is not really compliant/intuitive with the idea that the normalization is handled by the class itself.

**Comment by f-brinkmann** [comment]
At the moment, if you want an spectrum without any normalization there are two ways:

`signal.signal_type = 'energy'`
`spec = signal.freq`

and 

`spec = signal.freq`
`spec = pyfar.fft.normalization(spec, ..., inverse=True)`

The first would change the Signal, which might be undesired and the second requires in depth pyfar skills. In both cases, the user has to be aware of the Signal concept, otherwise errors are likely to occur. Workarounds to make the user aware of whats happening in the background might be to have a getter with an additional parameter `signal.freq(normalized=True)` or a second getter `signal.freq_raw`. The same applies for the setter.

**Comment by mberz** [comment]
tbh. I see this going in a direction where things start to get too bloated. Having multiple properties, which can change the spectrum normalization and then on top, a getter which ignores them all, or changes them is very misleading. Let me think about alternatives here.

**Comment by f-brinkmann** [comment]
We don't want this. Computer says no!
