### ISSUE TITLE
Unexpected Gain using high shelve filter with shelve type I and II

### ISSUE THREAD

**Issue by tjueterb** [pyfar/pyfar#392]
## General

* pyfar version: 0.5.1
* Python version: 3.10.4
* Operating System: MacOS 12.5.1
* Did you install pyfar via pip: yes

## Description

Using `pf.dsp.filter.high_shelve()` with the following explanation for the shelve type
```
shelve_type : str
Defines the characteristic frequency. The default is ``'I'``
    ``'I'``
        defines the characteristic frequency 3 dB below the gain value if
        the gain is positive and 3 dB above the gain value otherwise
    ``'II'``
        defines the characteristic frequency at 3 dB if the gain is
        positive and at -3 dB if the gain is negative.
    ``'III'``
        defines the characteristic frequency at gain/2 dB.
```
Using the high shelve filter with a gain of -6 dB and a characteristic frequency of 1 kHz I expected the gain at 1 kHz to be -3 dB, regardless of the shelve type. But the gain at 1 kHz turns out to be -4 dB using Type I and -2 dB using Type II.

## What I Did

```
import pyfar as pf
fs = 44100
frequency = 1000
gain = -6
order = 2

impulse = pf.signals.impulse(n_samples=fs, sampling_rate=fs)
for shelve_type in ['I', 'II', 'III']:
    ir = pf.dsp.filter.high_shelve(signal=impulse, frequency=frequency, gain=gain, order=order, 
                                   shelve_type=shelve_type)
    pf.plot.freq(ir, label=f'shelve type {shelve_type}')

plt.ylim((gain-1,+1))
plt.legend()
plt.show()
```

![output](https://user-images.githubusercontent.com/38947363/201658535-47247fb5-8705-43dd-ae4a-69ab9b2fecd6.png)

**Comment by f-brinkmann** [comment]
I think due to the transition the characteristic frequencies become exact for somewhat larger gains. If you are using 12 dB, everything is as expected. I'll double check with the Shelve-master. If this is the case, we could add a line to the docstring clarify.

```python
import pyfar as pf
import matplotlib.pyplot as plt
fs = 44100
frequency = 1000
gain = -12
order = 2

impulse = pf.signals.impulse(n_samples=fs, sampling_rate=fs)
for shelve_type in ['I', 'II', 'III']:
    ir = pf.dsp.filter.high_shelve(signal=impulse, frequency=frequency, gain=gain, order=order, 
                                   shelve_type=shelve_type)
    pf.plot.freq(ir, label=f'shelve type {shelve_type}')

plt.ylim((gain-1,+1))
plt.legend()
plt.show()
```

![image](https://user-images.githubusercontent.com/58219902/201748623-acedee24-48a0-4e68-bafa-b8b180af8a54.png)

**Comment by fs446** [comment]
Thanks for bringing this up.

I agree with @f-brinkmann to clarify the helping information in the docstring, as they are right now rather confusing.

Maybe it helps to introduce a variable $G$ for the level in dB. Then, level $G$ at specified frequency 
- is always $G /2$ for `type III` 
- is sign( $G$ ) $\cdot$ 3 dB for `type II`, this holds if $|G|$ is very large (such that the 3dB-cut off rule can be applied)
- is sign( $G$ ) $\cdot$ ( $|G|$ -3dB) for `type I`, again this holds if f $|G|$ is very large

Hope, these equations work this out. Can anybody double check them and insert them into the docstring?

Maybe, it is also worth to explain the characteristics for small $|G|$, but that would probably require some more math.

**Comment by f-brinkmann** [comment]
Thanks for clarifying. I double checked them - seems right to me. @tjueterb would you have time to prepare a pull for this next week?

**Comment by tjueterb** [comment]
@f-brinkmann I think so, yes!
