### ISSUE TITLE
Should we define a few test conventions/guidelines?

### ISSUE THREAD

**Issue by Agent49** [pyfar/pyfar#40]
1. Right now not all tests on the develop branch pass flake8. I think this is would be a good thing to take care of.
2. Decorators are mixed up e.g. `@pytest.fixture` and `@fixture`, do we want to be consistent or should it rather be everyone's own decision how to do that? I think that decorators should not get too long.
3. How to name mocks? Prefixing or suffixing: `mock_`, `m_`, `_mock` ...
4. (One-liner-)Docstrings or self-explaining test-names with docstrings only for fixtures/mocks? Or doesn't matter?

Please tell me if I go to far with those conventions, what your opinion about the above points are, or if you have things to add.

We could also discuss this on a meeting and write a short summary of the outcomes as a comment here below.

**Comment by mberz** [comment]
I was wondering about similar things recently and do agree, that the tests are starting to get a bit messy. Maybe it's a good idea to improve this in the very near future before it's too much work.

1. Sounds good to me.
2. I think it's not always the same fixture, that is being used, is it? Not sure on that one, please correct me here.
3. I like `mock_*`
4. Yes, docstrings are a good idea I think!

**Comment by Agent49** [comment]
It's the same: `from pytest import fixture`, I prefer the short version. Also `@patch` easily gets quiet long. 

I vote for either `m_*` or `mock_`.

In general I think that tests also should not get too verbose.

**Comment by mberz** [comment]
Ah, yes, in that case lets do the shortened version.

**Comment by f-brinkmann** [comment]
I agree with the above and had an additional idea:

It might be good to have a brief set of standard tests that all functions have to pass if they take and return Signals:
- Did the input signal remain unchanged
- Can the function handle 1-, 2-, N-dimensional arrays
- Was the meta-data of the input Signal correctly copied to the output Signal

What do you think? how would we go about that?

**Comment by sikersten** [comment]
Another aspect we should discuss is how to create baseline files to be tested against. Currently, we have at least to approaches implemented: for plots its done by indicating the creation with a flag in the test_plot.py, for io its done separately in generate_test_io_data.py. What to you prefer and which aspects are important to consider in this context?

**Comment by f-brinkmann** [comment]
> 
> 
> Another aspect we should discuss is how to create baseline files to be tested against. Currently, we have at least to approaches implemented: for plots its done by indicating the creation with a flag in the test_plot.py, for io its done separately in generate_test_io_data.py. What to you prefer and which aspects are important to consider in this context?

Having it in the same file is less maintenance but prone to the error of forgetting to reset the flag to false. Having separate files is more maintenance and prone to the error of doing different things in both files thus causing the tests to fail (This happened with the plot tests before and is why we have one test file now). Out of these two I prefer low maintenance. However, there might be a better solution: There is a pytest plugin for Matplotlib that sets the flag outside the tests themselves. Maybe we can come up with a similar solution that works for all cases - we might have more of them in the future and a separate plugin for all seems cumbersome.

**Comment by f-brinkmann** [comment]
Output of group discussion: We will use environment variables for flagging if external test data should be generated. The tests that use this will have a docstring that gives the name of the env. variable (and how to set it in unix/windows).
