### ISSUE TITLE
Class for non-equidistant audio data

### ISSUE THREAD

**Issue by f-brinkmann** [pyfar/pyfar#42]
## Description

Signal is great, but its data has to be sampled at equidistant times/frequencies, which is not always the case. Should we have a rather simple class that can store time/freq data at user specified times/frequencies?

**Comment by mberz** [comment]
I have already been thinking about this. That's why there's a parent class for Signal.
Are there specific use cases you're thinking about? I was primarily thinking about Incomplete DFT spectra resulting from simulations.
Maybe we can collect the most used cases here.

**Comment by f-brinkmann** [comment]
Good Idea - here's my candidates:
- Incomplete spectra (e.g., from numerical simulations)
- Fractional octave spectra (e.g., room acoustical parameters, musical instrument directivities)
- Incomplete time signals (e.g., due to drop-outs or clipping)

**Comment by f-brinkmann** [comment]
Output of group discussion:
- `Audio()` will be the parent class for signal and the new class
- `Audio` will be renamed to name for the new class up for suggestions
