### ISSUE TITLE
CONTRIBUTING.rst wrong CI link

### ISSUE THREAD

**Issue by pingelit** [pyfar/pyfar#424]
## General

* pyfar version: 0.5.1

## Description

In `CONTRIBUTING.rst` under __Pull Request Guidelines__ it links to __travis CI__ instead of __circle CI__. I am guessing this is wrong as it geves a 404 page error.

**Comment by f-brinkmann** [comment]
I think that is already fixed in develop

**Comment by pingelit** [comment]
As far as I can see, not on the develop currently online.

**Comment by f-brinkmann** [comment]
Oh, yes sorry. Its here #407

**Comment by pingelit** [comment]
Ah yes, I didn't see that one.
