### ISSUE TITLE
Calculations for Signal containing NaN elements return only NaN.

### ISSUE THREAD

**Issue by twennemann** [pyfar/pyfar#431]
If a Signal object including NaN values is used for a calculation, every value will be returned with NaN. Example:
`calc = pf.Signal([1, 2, np.nan], 44100) / 2`
I would expect that `calc.time == [0.5, 1, nan]` but the actual result is `calc.time == [nan, nan, nan]`.

**Comment by f-brinkmann** [comment]
We decided to test for NaNs in the signal.time/freq setters. Signals must not contain any NaNs
