### ISSUE TITLE
read_sofa not working with Path object

### ISSUE THREAD

**Issue by sikersten** [pyfar/pyfar#437]
## General

* pyfar version: 0.5.2
* Python version: 3.10.9

## Description

Though the docstring of [io.read_sofa](https://pyfar.readthedocs.io/en/stable/modules/pyfar.io.html#pyfar.io.read_sofa) states that the filename could be a string or a pathlib.Path, it only works with strings. The reason is that  _filename.endswith(...)_ is called in [sofa.read_sofa()](https://sofar.readthedocs.io/en/latest/sofar.functions.html#sofar.read_sofa).
This could be fixed similar as in [io.read()](https://pyfar.readthedocs.io/en/stable/modules/pyfar.io.html#pyfar.io.read) with something like `filename = pathlib.Path(filename).with_suffix('.sofa')` either in pyfar or sofar.
A workaround is to call _read_sofa_ with the Path object `filename` and `filename.as_posix()`.

## What I Did

```
import pyfar as pf
from pathlib import Path
filename = Path('file.sofa')
sofa, r_coords, s_coords = pf.io.read_sofa(filename)

AttributeError: 'WindowsPath' object has no attribute 'endswith'
```

**Comment by f-brinkmann** [comment]
I think `sofar.read_sofa` was never intended to be used with path objects (https://sofar.readthedocs.io/en/stable/sofar.functions.html#sofar.read_sofa). But it would be a simple fix and we should add this to the up-comming sofar release. I'll add an issue at sofar

**Comment by f-brinkmann** [comment]
This is now fixed in sofar and is sheduled for the next feature release
