### ISSUE TITLE
Harmonize Contributing guidelines across pyfar packages

### ISSUE THREAD

**Issue by f-brinkmann** [pyfar/pyfar#454]
## General

We want to write the CONTRIBUTING.rst in a way that it can be used for all pyfar packages. Other packages will then link to the pyfar guide lines and add package specific information. Requires #407 
Options
- https://sublime-and-sphinx-guide.readthedocs.io/en/latest/reuse.html
- ...

**Comment by ahms5** [comment]
done? @f-brinkmann

**Comment by f-brinkmann** [comment]
Yes
