### ISSUE TITLE
Transfer and update cookiecutter template

### ISSUE THREAD

**Issue by sikersten** [pyfar/pyfar#455]
It would be useful to transfer the cookiecutter template by @mberz to the pyfar organization, and update it according to our current workflow.

- [x] transfer, new location: [pyfar/cookiecutter-pypackage](https://github.com/pyfar/cookiecutter-pypackage)
- [x] update

**Comment by mberz** [comment]
Currently located here: https://github.com/mberz/cookiecutter-pypackage

**Comment by f-brinkmann** [comment]
@ahms5 - this can be closed, right?
