### ISSUE TITLE
Cannot import pyfar when working with write protected images (Singularity)

### ISSUE THREAD

**Issue by adku1173** [pyfar/pyfar#495]
## General

* pyfar version: 0.5.3
* Python version: 3.9
* Operating System: Ubuntu (Singularity Container)
* Did you install pyfar via pip: yes

## Description

I tried to import pyfar from a Python instance running inside a singularity container. However, since I do not have any permission to create a directory inside a write protected image, an error was raised related to the following line:

https://github.com/pyfar/pyfar/blob/a556fb93a6a3e0ea1d196726a89dad30095a422b/pyfar/signals/files.py#L27-L31
There should be some way to manually specify the file path. Alternatively, I believe it would be better to only create the directory if needed.

**Comment by f-brinkmann** [comment]
I'm not sure if we want to handle user specific paths, since it would require some sort of preference file, which might cause follow up issues. I will leave this for discussion in the weekly. Here is a quick fix for now: https://github.com/pyfar/pyfar/tree/fix/run_in_read_only_containers
