### ISSUE TITLE
Account for deprecation of `matplotlib.tight_layout` module

### ISSUE THREAD

**Issue by f-brinkmann** [pyfar/pyfar#501]
## General

* pyfar version: 0.5.4
* Matplotlib version: >=3.8

## Description

Matplotlib is deprecating the `matplotlib.tight_layout`. It contains the function `get_subplotspec_list` that we use to check if `tight_layout` should be applied to a figure. Without this check, using `tight_layout` may result in figures with overlapping elements. This happens for example for a 2,1 subplot layout with a shared colorbar on the side (see example below).

## Possible solution

We could use [constrained](https://matplotlib.org/stable/users/explain/axes/constrainedlayout_guide.html) layout as the new default (see example below). It used to be experimental but seems to be stable now. It works in most cases with few exceptions only, and it seems to be further improved.

## Implementation

Constrained layout can be enabled via the plotstyle by setting `figure.constrained_layout.use : True`. I would suggest to add two new plotstyles *light_constrained.mplstyle* and *dark_constrained.mplsytle*. The former would be the new default in favor of *light.mplstyle*. This would save a bunch of code in pyfar and maintain full flexibility. If using *light.mplstyle* manual layout or `tight_layout` could be applied to a figure before or after plotting with pyfar. I tested it offline and it seems to work.

```python
import matplotlib.pyplot as plt
import numpy as np

for layout in ['tight', 'constrained']:
    np.random.seed(19680801)
    fig, axs = plt.subplots(2, 1, figsize=(2, 2), layout=layout)
    img = axs[0].pcolormesh(np.random.rand(10, 20))
    axs[1].pcolormesh(np.random.rand(10, 20))
    fig.colorbar(img, ax=axs, orientation='vertical', fraction=.1)
    plt.show()

    fig.savefig(f'test_{layout}.png')
    plt.clf()
```

Tight Layout
![test_tight](https://github.com/pyfar/pyfar/assets/58219902/8ef8f149-7d76-45d5-912f-01e890e4db36)

Constrained Layout
![test_constrained](https://github.com/pyfar/pyfar/assets/58219902/4bd054ea-f5fe-4fc8-940d-e3c21a6fd929)

**Comment by sikersten** [comment]
Thanks for noting, definitely a necessary enhancement! I might be missing something here. What's your idea behind adding two new plotstyles instead of adding `figure.constrained_layout.use : True` to the already existing? In other words, does adding `figure.constrained_layout.use : True` change any appearence other plots, such as simple 1x1 lineplots?
