### ISSUE TITLE
Improve docs and import structure

### ISSUE THREAD

**Issue by f-brinkmann** [pyfar/pyfar#506]
## General

* pyfar version: 0.5.4

## Description

- [x] Unify documentation of classes, especially of magic functions like `__init__`

**Comment by artpelling** [comment]
Maybe add the sorting of import blocks to the list?

**Comment by f-brinkmann** [comment]
Do you mean the `import ...` statements in the Python files?

**Comment by artpelling** [comment]
> Do you mean the `import ...` statements in the Python files?

Yes. Maybe that is unrelated, though...
