### ISSUE TITLE
 `find_within` bug with `distance_measure='spherical_radians'`

### ISSUE THREAD

**Issue by jinnsjj** [pyfar/pyfar#523]
## General

* pyfar version: 0.6.1
* Python version: 3.9.1
* Operating System: MacOS
* Did you install pyfar via pip: yes

## Description

`find_within` bug with `distance_measure='spherical_radians'`
 
## What I Did

I want to use pf to find all point on the northern hemisphere, I used scripts below. It returns a crash.

```
find = pf.Coordinates(0, 0, 1)
spatial_mask = coords.find_within(
    find,
    distance=np.pi/2,
    distance_measure='spherical_radians',
    atol=0.1)
coords.show(spatial_mask[0])
```

I located bug here, change `==` to `in` help me solve the problem.

```
        if distance_measure == ['spherical_radians', 'spherical_meter']:
            # determine validate radius
            radius = self.radius
            delta_radius = np.max(radius) - np.min(radius)
            if delta_radius > 1e-15:
                raise ValueError(
                    "find_nearest_sph only works if all points have the same \
                    radius. Differences are larger than 1e-15")
            radius = np.max(radius)

```

furthermore, I'm interseted in the delta_radius, 1e-15 is very small so that float value is hard to satify this threshold. Could we consider lowering the threshold?

**Comment by ahms5** [comment]
Thanks for reporting the bug, this should be fixed with pr #524. For the radius, I proposed an optional parameter to override the default.
