### ISSUE TITLE
Refactor Example Notebooks

### ISSUE THREAD

**Issue by f-brinkmann** [pyfar/pyfar#528]
## Description

- We decided to create multiple example notebooks by merging and extending the [Concepts section](https://pyfar.readthedocs.io/en/stable/concepts.html) and the [example notebook](https://github.com/pyfar/pyfar/tree/main/examples).
- Notebooks for general Tasks and Application examples could get separate sections on readthedocs which are moved to www.github.com/pyfar/gallery

General tasks

- [x] Include notebooks in readthedocs (see sofar and spharpy, e.g. https://spharpy--49.org.readthedocs.build/en/49/)
- [x] Find best way to link between notebooks and other parts of readthedocs
- [x] Adapt to the new gallery

Remainder of this issue was moved to https://github.com/pyfar/gallery/issues/12

**Comment by sikersten** [comment]
For example notebooks which use several pyfar packages we should consider creating a separate repository (a pyfar application gallery).

**Comment by pingelit** [comment]
I can do the binaural synthesis as well.

**Comment by f-brinkmann** [comment]
great, go ahead :)

**Comment by mberz** [comment]
I'll move the planning of new notebooks part of this issue to the gallery repository.
