### ISSUE TITLE
type checking in `Signal.sampling_rate`

### ISSUE THREAD

**Issue by artpelling** [pyfar/pyfar#533]
The `sampling_rate` kwarg in the `Signal` constructor is not thoroughly typechecked or parsed which leads to errors down the line that are hard to backtrace. IMO `sampling_rate` should be cast as an integer. Of course having `sampling_rate` as a 2d-array is not a great design choice but happens sometimes, e.g. when reading data from `.mat` files

 
MWE:
``` python
import numpy as np
import pyfar as pf

n = np.random.rand(100)
fs = np.array([[100]])
sig = pf.Signal(n, sampling_rate=fs)
pf.plot.group_delay(sig) # this fails
```

**Comment by f-brinkmann** [comment]
I think we once discussed that it should be possible to have float sampling rates to be most flexible, but it definately should not be an array. We could cast it to int, if it does not have a decimal. Would that be a good compromise?

**Comment by f-brinkmann** [comment]
Ah, yes - that would be needed but would not cast to integer. But it works woth float as desired:

```pythaon
signal = pf.Signal([0, 1, 0, 0], 22.5)
gd = pf.dsp.group_delay(signal)
```

**Comment by artpelling** [comment]
Regarding casting to integer: I noticed that a `float` fails when writing to file, i.e.

``` python
pyfar.io.write_audio(pyfar.Signal(array, sampling_rate=44100.0))
```
will fail. I think writing to file should round to the nearest integer, cast the type and throw a warning on nonzero roundoff. What do you think?

**Comment by f-brinkmann** [comment]
Can you check your pyfar version. It works for me in 0.6.3 and only thros an error if acutally having a non integer sampling rate. We fixed it a while ago following the idea you also have :)
