### ISSUE TITLE
Plot phase minor locator at base 2 fractions

### ISSUE THREAD

**Issue by sikersten** [pyfar/pyfar#540]
## General

* pyfar version: 0.6.3

## Description
Currently, the default ticklabels in phase plots are at 0, +/- $\pi$/2, +/- $\pi$. The minor locators (thin lines) are at multiples of $\pi/6$.
In my opinion, minor locators at multiples of $\pi/4$ or $\pi/8$ are more meaningful (see below). These would be consistent with other typical ways of showing the phase, e.g., degree in multiples of 360/4, cycles/periods in multiples of 1/4...
## What I Did

```
import pyfar as pf
import numpy as np
import matplotlib.pyplot as plt
from pyfar.plot.ticker import MultipleFractionLocator, MultipleFractionFormatter

fig, ax = plt.subplots(3, 1)
signal = pf.signals.noise(1e3)
pf.plot.phase(signal, ax=ax[0])
pf.plot.phase(signal, ax=ax[1])
pf.plot.phase(signal, ax=ax[2])
ax[0].set_title("Multiples of $\pi/6$ (default)")
ax[1].yaxis.set_minor_locator(MultipleFractionLocator(np.pi, 4))
ax[1].set_title("Multiples of $\pi/4$")
ax[2].yaxis.set_minor_locator(MultipleFractionLocator(np.pi, 8))
ax[2].set_title("Multiples of $\pi/8$")
```
![image](https://github.com/pyfar/pyfar/assets/70263411/6b7502ce-f70f-422b-879b-d2af47dd4881)

**Comment by f-brinkmann** [comment]
+1 for changing this, but we have to make sure to redo the base plots for phase in the tests.
