### ISSUE TITLE
Example notebook not tested on Travis or other CI

### ISSUE THREAD

**Issue by mberz** [pyfar/pyfar#55]
## Description

The example notebook is currently not tested on Travis; let's change that since it's a pretty important part of the documentation.
A feasible option might be running with nbconvert.

**Comment by alex-treebeard** [comment]
Hey mberz, I've just released [nbmake](https://github.com/treebeardtech/nbmake) which may help here. I'm keen to hear feedback if you try it out.

**Comment by mberz** [comment]
Thanks, I'll check it out!
