### ISSUE TITLE
Unexpected output when plotting phase of an FIR filter

### ISSUE THREAD

**Issue by mfreeborn** [pyfar/pyfar#603]
I strongly suspect this is user error on my part, but I thought I'd double check here.

I'm trying to visualise a FIR filter, using taps generated by [rePhase](https://rephase.org/). 

The graphical output of the filter on rePhase is as follows; note the phase is 0° across the frequency range.

![fir_taps_rephase](https://github.com/pyfar/pyfar/assets/31806808/cd755147-6da1-4542-88ef-4fac3e795fc2)

When I take the generated taps, create a pyfar `FilterFIR` object and process it against an impulse, I get the following:

![pyfar_fir_plot](https://github.com/pyfar/pyfar/assets/31806808/ef332a3d-113f-4751-b2e6-eaa18f4f8d7a)

The amplitude line is the same as on rePhase, but the phase is all over the place. I'm sure pyfar is plotting it correctly according to the settings I have chosen, but what am I missing that the phase isn't 0° throughout?

The sampling rate is 192,000Hz throughout. 

pyfar version is 0.6.5.

pyfar code:

```python
import matplotlib.pyplot as plt
from pyfar.classes.filter import FilterFIR
from pyfar.plot import freq_phase
from pyfar.signals import impulse

coeffs = [
    see attached...
]

i = impulse(48000, sampling_rate=192000)
f = FilterFIR(coeffs, sampling_rate=192000)
s = f.process(i)

freq_phase(s, deg=True, unwrap=False)
plt.show()

```
[coeffs.txt](https://github.com/pyfar/pyfar/files/15220251/coeffs.txt)

**Comment by f-brinkmann** [comment]
Can you add a figure using `pf.plot.time`? A zero phase filter should be symmetric around time=0. BTW, you can also directly load the coeffs into a signal object, if you want: `s = pf.Signal(coeffs, 192000)`

**Comment by mfreeborn** [comment]
Thanks for the reply: updated code:

```python
import matplotlib.pyplot as plt
import pyfar as pf
import pyfar.plot as pfp

coeffs = [
    attached to previous post
]

f, (ax1, ax2, ax3) = plt.subplots(3, 1, layout="constrained")
s = pf.Signal(coeffs, 192000)

pfp.freq(s, ax=ax1)
pfp.phase(s, deg=True, unwrap=False, ax=ax2)
pfp.time(s, ax=ax3)
plt.show()
```

Output:

![freq_phase_time](https://github.com/pyfar/pyfar/assets/31806808/0bd52c84-06a2-44d5-b3bd-d2295f95f9e1)

**Comment by f-brinkmann** [comment]
Thanks, this is clearly not zero-phase - I suspect that rePhase is not plotting the actual phase of the filter, or that the phase response somehow changed through the export...

**Comment by mfreeborn** [comment]
Thanks for the confirmation, I'll raise a support issue with rePhase.

**Comment by mfreeborn** [comment]
Ah, if I may, I think the issue is handling the delay of the filter. I've used some different plotting software and I think I can see where it's going wrong.

Each of the following graphs is the same 1024 tap FIR filter (just a simple high pass filter), the first graph shows the askew phase with no offset applied and the second shows linear phase _with_ the offset applied. The offset, in number of samples, is part of the output from rePhase when one designs the filter.

![holm impulse no offset](https://github.com/pyfar/pyfar/assets/31806808/fd89ba4c-89e0-449f-845f-a9dd2aad0068)

![holm impulse with offset](https://github.com/pyfar/pyfar/assets/31806808/ddcb3f3e-0e0f-447a-afcc-49f93a6154db)

I've tried all variations in pyfar trying to replicate this delay, but try as I might, I can't.

With the following code, I get the below output.

```python
import matplotlib.pyplot as plt

import pyfar as pf
import pyfar.classes.filter as pff
import pyfar.plot as pfp

coeffs = [attached]

# FIR filter with 1024 taps representing a 3k LR high pass filter
fir_filter = pff.FilterFIR(coeffs, sampling_rate=192000)
# Same but just as a plain signal for plotting purposes
fir_signal = pf.Signal(coeffs, sampling_rate=192000)


# unit impulse with 512 sample delay - this is the offset that rePhase says
# applies to this filter
imp = pf.signals.impulse(1024, sampling_rate=192000, delay=512)

# process the impulse signal against the FIR filter
filtered_signal = fir_filter.process(imp)

# plotting
f, ((ax1, ax2, ax3), (ax4, ax5, ax6)) = plt.subplots(2, 3, layout="constrained")
pfp.freq(fir_signal, ax=ax1)
pfp.phase(fir_signal, ax=ax2, deg=True)
pfp.time(fir_signal, ax=ax3, unit="ms")
pfp.freq(filtered_signal, ax=ax4)
pfp.phase(filtered_signal, ax=ax5, deg=True)
pfp.time(filtered_signal, ax=ax6, unit="ms")
plt.show()
```

![impulse delay](https://github.com/pyfar/pyfar/assets/31806808/21524af3-f1ad-45dc-885d-89e85334f380)

[coeffs_1024.txt](https://github.com/pyfar/pyfar/files/15238092/coeffs_1024.txt)

**Comment by mberz** [comment]
I'm not sure if I understand you correctly.
If you want to remove the time shift applied by rePhase, you can either use [pyfar.dsp.time_shift](https://pyfar.readthedocs.io/en/stable/modules/pyfar.dsp.html#pyfar.dsp.time_shift) or simply force the coefficients to be zero-phase again by using `pyfar.dsp.zero_phase`.

``` python
s = pf.Signal(coeffs, 192000)
n_samples = 1024 # insert you number of samples you want to shift here.
pf.dspl.time_shift(s, -n_samples)
```

From what I can see of the input fields in your rePhase screenshot, it seems though as if the impulse response of the filter may also time windowed, which generally is a good idea when approximating a IIR filter with FIR filter, but may also introduce differences between the results seen in rePhase and pyfar.

**Comment by mfreeborn** [comment]
You've nailed it - `time_shift` with the given number of samples to offset by has solved it. Phase is now linear; impulse is symmetric around 0s, great! Interestingly, whilst the default mode `cyclic` results in linear phase, setting it to `linear` results in the set of plots as row 2 in my previous comment (`process`ing a delayed impulse against the FilterFIR object). 

Thanks both for your inputs, I've learned a lot along the way.

**Comment by mberz** [comment]
The `linear` option in time shift shifts the IR to the left and "removes" all prior samples. To maintain the length of the IR, zeros are padded at the end corresponding to the number of shifted samples. In your case, that results in removing half of the filters IR, which is why the spectrum and phase do not resemble the original ones any more.
