### ISSUE TITLE
Pink noise distorts heavily on rms=1

### ISSUE THREAD

**Issue by steckes** [pyfar/pyfar#623]
## General

* pyfar version: 0.6.6
* Python version: 3.10.14
* Operating System: Linux 6.9.3-arch1-1 x86_64
* Did you install pyfar via pip: yes

## Description

Generating noise with rms=1 is leading to clipping because many values > 1.0 are produced. Especially with pink noise, this leads to an extremely distorted sound.
Is the solution to set the default to something lower than 1 or is there something that could be improved in the leveling part of the noise function?

## What I Did

```
noise = pyfar.signals.noise(44100, "pink", 1, 44100)
pyfar.io.write_audio(noise, "noise.wav")
```

Warning: `UserWarning: wav-files of subtype PCM_16 are clipped to +/- 1.`

**Comment by f-brinkmann** [comment]
Hi Stephan, we probably won't change the noise function itself but I guess this would help #624. The information is also contained in the docs, but I would also have to blame myself for not reading all docstrings until the end 🙈
