### ISSUE TITLE
creshape and cflatten for Signal class

### ISSUE THREAD

**Issue by f-brinkmann** [pyfar/pyfar#63]
It would be nice if Signal hat a channel_reshape `creshape()` and channel_flatten function that return copies of the signal with another channel layout. Implementation will be analogous to np.flatten and np.reshape, but the last dimension (n_samples, n_bins) can not be changed.

A use case are the private plot functions (_line.*) and Interaction that require 2D arrays

**Comment by mberz** [comment]
I would rather name these functions `reshape` and `flatten`, adding a c for channel is redundant and in my opinion only confusing.

**Comment by mberz** [comment]
Linked to #58 related to copy methods.
