### ISSUE TITLE
`high_shelve_filter` and `low_shelve_filter` always return 1 section when N=None

### ISSUE THREAD

**Issue by mfreeborn** [pyfar/pyfar#641]
## General

* pyfar version:
0.6.8

* Python version:
3.12.3

* Operating System:
Ubuntu 24.04

* Did you install pyfar via pip:
Yes

## Description
I'm using the `high/low_shelve_cascade` functions to create IIR filters comprised of second order sections. I provide the frequency, sampling rate, gain and slope, and therefore let the function calculate the correct bandwidth and optimal number of sections (i.e. I leave `N` to be the default `None`).

Regardless of the parameters I provide, the function always returns a `FilterSOS` with a single section. I variously get warnings that the bandwidth is too narrow, but I'm not sure that's relevant to the number of sections returned.

I would, perhaps naively, expect the number of sections to increase as `slope` increases. My comparison is the program [REW](https://www.roomeqwizard.com/), which generates 1 section for slopes 6 and 12dB/oct, 2 sections for slopes 18 and 24dB/octave, and so on.

Here's a quick example:

```python
import pyfar.dsp.filter as pff
hs = pff.high_shelve_cascade(signal=None, frequency=1000, gain=-10, slope=-48, sampling_rate=48000, N=None)

# hs[0].n_sections == 1
# a warning is raised: /home/michael/programming/scratch/.venv/lib/python3.12/site-packages/pyfar/dsp/filter/audiofilter.py:496: UserWarning: The bandwidth is 0.20833333333333334 octaves but should be at least 1 to obtain an good approximation of the desired frequency response
  warnings.warn((
```

The identical filter in `REW` yields an SOS filter with 4 sections.

Is this correct behaviour, or should I indeed expect `pyfar` to always yield single-section SOS filters?

(as an aside, grammatically I believe these functions should be `shelf`, not `shelve`. Or, at a push, `shelving`, but the first suggestion seems to be far more common)

**Comment by f-brinkmann** [comment]
Hi Michael, I don't remember the implementation details from the top of my head but it seems correct to me at first glance. Accordings to the docs the bandwidth is calculated as `bandwidth = abs(gain/slope)=0.2`,  but should be 1 or larger as indicated by the warning. The filter reaches -10 dB as desired, but cant reach it within the specified bandwidth. Manually increasing the order to `N=4` affects the magnitude response of the filter only marginally.

Is REW referencing to the same paper from Schultz et al.? How is their bandwidth defined?

Thanks for the hint with the grammer - we'll change that.
