### ISSUE TITLE
Provide plot functionality for `TimeData` and `FrequencyData`

### ISSUE THREAD

**Issue by f-brinkmann** [pyfar/pyfar#82]
## Description

Currently, the plot functions only work for objects of the `Signal` class. Extending them for the new audio classes should be easy. In the best case, extending the check for the instance at the beginning of each plot function might already do the trick.

**Comment by sikersten** [comment]
Good point! Do you implement the corresponding new stubs as part of this?

**Comment by f-brinkmann** [comment]
> 
> 
> Good point! Do you also implement the corresponding new stubs?

Yes, looks like it is my turn to take one for the team :)
