### ISSUE TITLE
Unexpected plot behavior for subplots

### ISSUE THREAD

**Issue by sikersten** [pyfar/pyfar#95]
## Description

I'd like to plot different signals in subplots. Depending on how the figure is initialized, some pyfar plot properties (colors, grid...) are overwritten be the matplotlib defaults. This is a little unexpected as it is possible to pass the axes object.

## What I Did

```
import pyfar
import matplotlib.pyplot as plt
import numpy as np

signal = pyfar.Signal(np.random.rand(2,1000), sampling_rate=44100)
# Figure with pyfar properties
fig = plt.figure()
pyfar.plot.time(signal)
# Figure with matplotlib defaults
fig, ax = plt.subplots(1,1)
pyfar.plot.time(signal, ax=ax)
```

**Comment by f-brinkmann** [comment]
I think in the second example, the Matplotlib default style is applied to the axes as soon as they are created. There would be two ways to get the pyfar styles in this case:

1. Explicitly use the plotstyle
```
with plt.style.context(pyfar.plot.utils.plotstyle()):
    fig, ax = plt.subplots(1, 1)
pyfar.plot.time(signal, ax=ax)
```

2. have a subplot function in pyfar that wraps the subplot function in Matplotlib and does the above by default.

I think the second option would be a good way to go and could be used for gridspec as well. Any opinons?

**Comment by f-brinkmann** [comment]
ps: In your first example, the figure also does not have the pyfar style. This becomes obvious when using the dark theme:
```
fig = plt.figure()
pyfar.plot.time(signal, style='dark')
```

**Comment by sikersten** [comment]
Ok, I only paid attention to the colors, these are pyfar defaults in the first example, aren't they?
A subplot wrapper would be very useful! I'm not quite sure on what to do about the results produced by the dark style, should we handle this as faulty use?

**Comment by f-brinkmann** [comment]
Solution: `pyfar.plot.utils.plotstyle()` will become a context manager that can be used this way
```
with pyfar.plot.utils.plotstyle():
   # some plot
```

Will be done after #84 is closed.
